### ISSUE TITLE
Improve crates.io presence

### ISSUE THREAD

**Issue by WaDelma** [WaDelma/poisson#9]
- [ ] Categories
- [ ] docs.rs as documentation host (remove github.io based one)

**Comment by ctbur** [comment]
The crate on crates.io was last updated 2 years ago. Would you mind publishing a new version?

**Comment by WaDelma** [comment]
I probably should. Last time I worked on this I tried to get visualisation working so I could fix a bug and then work took all my time and didn't continue with it.

**Comment by ctbur** [comment]
Great, thanks!
